CREATE TABLE IF NOT EXISTS `b_fix_comments` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `ACTIVITY_ID` int(11)  unsigned NOT NULL,
  `DATE_ADD` DATETIME NOT NULL,
  `DATE_START` DATETIME NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
